[package]
name = "financeflow"
version = "1.0.0"
authors = ["devnulldevG"]

[dependencies]
MoveStdlib = { git = "https://github.com/move-language/move", subdir = "language/move-stdlib" }
DiemFramework = { git = "https://github.com/diem/diem", subdir = "language/diem-framework/modules" }
